#!/bin/bash

# init will deploy vault only and ensure it is initialised.
set -x

EXECDIR="$(pwd)"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR

# terragrunt run-all apply --terragrunt-source-update --terragrunt-non-interactive
terragrunt run-all apply --terragrunt-source-update --terragrunt-non-interactive

cd $EXECDIR