#!/bin/bash

# defaults
resourcetier="dev"
targetdir="/aws/mde/tmp"

set -e

aws sts get-caller-identity

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR
dirname=${SCRIPTDIR##*/}

git pull origin
./gitpullrecursive --init-all


sudo mkdir $targetdir
sudo chown $USER $targetdir
sudo cp -fr $SCRIPTDIR $targetdir/.
cd $targetdir/$dirname

./install-packages
source ./update_vars.sh --resourcetier $resourcetier
./init/init