#!/bin/bash

# defaults
resourcetier="dev"

set -e

aws sts get-caller-identity

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR
dirname=${SCRIPTDIR##*/}
targetdir="/aws/mde/tmp"

echo "pwd: $PWD"
git pull origin
./gitpullrecursive --init-all

sudo mkdir -p $targetdir
sudo chown $USER:$USER $targetdir
sudo chmod +rwX $targetdir
cp -fr $SCRIPTDIR /aws/mde/tmp/.
cd $targetdir/$dirname

./install-packages
source ./update_vars.sh --resourcetier $resourcetier
./init/init-aws-shell