#!/bin/bash

# defaults
resourcetier="dev"

set -e

aws sts get-caller-identity

SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
cd $SCRIPTDIR

dirname=${SCRIPTDIR##*/}
targetdir="/aws/mde/tmp"

echo "pwd: $PWD"
git pull origin
./gitpullrecursive --init-all

sudo mkdir -p $targetdir
sudo chown $USER:$USER $targetdir
sudo chmod +rwX $targetdir
if [[ -d "$targetdir/$dirname" ]]; then # clean dir if exist
  rm -fr "$targetdir/$dirname"
fi
cp -fr $SCRIPTDIR $targetdir/.
cd $targetdir/$dirname

./install-packages
./app/scripts/destroy_deployment