#!/bin/bash

set -e
# set -x

aws sts get-caller-identity

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR

SUDOCMD="sudo" # replace with text sudo to use elevated permissions

$SUDOCMD yum install -y python
$SUDOCMD yum install -y python3.7
$SUDOCMD yum install -y python3-pip # for a specific python version - https://realpython.com/intro-to-pyenv/

$SUDOCMD yum install -y jq
mkdir -p $SCRIPTDIR/tmp

wget https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip -P /tmp/ --quiet # Get terraform
$SUDOCMD unzip /tmp/terraform_0.13.7_linux_amd64.zip -d /tmp/
$SUDOCMD mv /tmp/terraform /usr/local/bin/.

wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.30.3/terragrunt_linux_386 -P /tmp/ --quiet # Get Terragrunt
$SUDOCMD mv /tmp/terragrunt_linux_386 /usr/local/bin/terragrunt
$SUDOCMD chmod +x /usr/local/bin/terragrunt

mkdir -p "$HOME/.ssh/tls" # The directory to store TLS certificates in.

# echo "Resizing EBS volume..."
# $SCRIPTDIR/deploy/firehawk-main/scripts/resize.sh