#!/bin/bash

terraform_version="0.13.7"
terragrunt_version="0.30.3"

set -e
# set -x

aws sts get-caller-identity

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
cd $SCRIPTDIR

SUDOCMD="sudo" # replace with text sudo to use elevated permissions

$SUDOCMD yum install -y python
$SUDOCMD yum install -y python3.7
$SUDOCMD yum install -y python3-pip # for a specific python version - https://realpython.com/intro-to-pyenv/

$SUDOCMD yum install -y jq
mkdir -p $SCRIPTDIR/tmp

if terraform --version | grep -nq "Terraform v$terraform_version"; then
    echo 'terraform already installed'
else
    wget https://releases.hashicorp.com/terraform/$terraform_version/terraform_${terraform_version}_linux_amd64.zip -P /tmp/ --quiet # Get terraform
    $SUDOCMD unzip /tmp/terraform_${terraform_version}_linux_amd64.zip -d /tmp/
    $SUDOCMD mv /tmp/terraform /usr/local/bin/.
fi

if terragrunt --version | grep -nq "terragrunt version v$terragrunt_version"; then
    echo 'Terragrunt already installed'
else
    wget https://github.com/gruntwork-io/terragrunt/releases/download/v$terragrunt_version/terragrunt_linux_386 -P /tmp/ --quiet # Get Terragrunt
    $SUDOCMD mv /tmp/terragrunt_linux_386 /usr/local/bin/terragrunt
    $SUDOCMD chmod +x /usr/local/bin/terragrunt
fi

mkdir -p "$HOME/.ssh/tls" # The directory to store TLS certificates in.

# echo "Resizing EBS volume..."
# $SCRIPTDIR/deploy/firehawk-main/scripts/resize.sh