#!/bin/bash

set -e

EXECDIR="$(pwd)"
SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
cd $SCRIPTDIR

bucket_name="$(terragrunt output --raw bucket_name)"

# "https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/create/review
#    ?templateURL=https://s3.eu-central-1.amazonaws.com/cloudformation-templates-eu-central-1/WordPress_Single_Instance.template
#    &stackName=MyWPBlog
#    &param_DBName=mywpblog
#    &param_InstanceType=t2.medium
#    &param_KeyName=MyKeyPair"

template_url="https://s3.amazonaws.com/${bucket_name}/cloudformation_ssm_parameters_firehawk.yaml"

quick_create_url="https://console.aws.amazon.com/cloudformation/home?region=${AWS_DEFAULT_REGION}#/stacks/create/review?templateURL=${template_url}&stackName=SSMParametersFirehawk"

echo 
echo "Configuration instructions:"
echo
echo "If this is your first time deploying:"
echo
echo "  1.  After completing the UBL Instructions provided in this log above, continue."
echo "      Without the UBL credentials .zip in your bucket, you can't render with deadline."
echo
echo "  2.  Goto the codepipeline page and edit tf-firehawk-deploy-pipeline."
echo "      Edit the stage 'source' and you should see an option to complete your github credentials."
echo
echo "  3.  You must configure more parameters before deployment using the cloudformation template"
echo "      URL below."
echo "      If you have already done this, and only want to make changes, do not use this link."
echo "      Instead, go to Cloudformation in the AWS Console and update the template manually."
echo
echo "      ${quick_create_url}"
echo
echo "  4.  You are now ready to start the codepipeline in the console and deploy."

cd $EXECDIR