#!/bin/bash

set -e

bucket_name="$(terragrunt output bucket_name)"

# "https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/create/review
#    ?templateURL=https://s3.eu-central-1.amazonaws.com/cloudformation-templates-eu-central-1/WordPress_Single_Instance.template
#    &stackName=MyWPBlog
#    &param_DBName=mywpblog
#    &param_InstanceType=t2.medium
#    &param_KeyName=MyKeyPair"

template_url="https://s3.amazonaws.com/${bucket_name}/cloudformation_ssm_parameters_firehawk.yaml"

quick_create_url="https://console.aws.amazon.com/cloudformation/home?region=${AWS_DEFAULT_REGION}#/stacks/create/review?templateURL=${template_url}&stackName=SSMParametersFirehawk"

echo 
echo "If this is your first time setting up:"
echo "  1.  Follow the UBL Instructions provided in this log.  Without the UBL credentials .zip, you can't render."
echo "  2.  You must configure more parameters before deployment using the cloudformation template here:"
echo "      ${quick_create_url}"
