#!/bin/bash

EXECDIR="$(pwd)"
SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
cd $SCRIPTDIR

s3_bucket_name="$(terragrunt output --raw s3_bucket_name)"

echo
echo "UBL Instructions:"
echo
echo "If you are using UBL for third party software, use the AWS Management Console"
echo "for S3 to place the zip file containing the certs you wish to configure for the"
echo "UBL license forwarder in the bucket path:"
echo
echo "${s3_bucket_name}/ublcertszip/certs.zip"
echo
echo "This cert zip file is provided by Thinkbox when you purchase UBL credits for"
echo "the first time for any software.  If you purchase credits for new software for"
echo "the first time you must update this file."

cd $EXECDIR