#!/bin/bash

set -e -x

EXECDIR="$(pwd)"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

cd SCRIPTDIR/../modules
zip -r codedeploy-app-firehawk.zip firehawk/*

aws s3 cp codedeploy-app-firehawk.zip s3://codedeploy.dev.firehawkvfx.com

aws deploy create-deployment \
  --application-name firehawk-codedeploy-app \
  --deployment-config-name CodeDeployDefault.OneAtATime \
  --deployment-group-name firehawk-deployment-group \
  --description "Firehawk deployment" \
  --s3-location bucket=codedeploy.dev.firehawkvfx.com,bundleType=zip,key=codedeploy-app-firehawk.zip

cd $EXECDIR