#!/bin/bash

set -e -x

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

zip -r $SCRIPTDIR/codedeploy-app-firehawk.zip $SCRIPTDIR/../modules/firehawk/*

aws s3 cp $SCRIPTDIR/codedeploy-app-firehawk.zip s3://codedeploy.dev.firehawkvfx.com

aws deploy create-deployment \
  --application-name firehawk-codedeploy-app \
  --deployment-config-name firehawk-deployment-config \
  --deployment-group-name firehawk-deployment-group \
  --description "Firehawk deployment" \
  --s3-location bucket=codedeploy.dev.firehawkvfx.com,bundleType=zip,key=codedeploy-app-firehawk.zip